
MCU_LDSCRIPT = nrf51822_slave
MCU_SERIES = NRF51822
NRFSDK_ROOT := ./NRF5_SDK

NRF_SEPARATE = slave

#NRFCFLAGS += -DNRF_LOG_BACKEND_SERIAL_USES_UART=1
#NRFCFLAGS += -DNRF_LOG_BACKEND_SERIAL_UART_TX_PIN=19
