
MCU_LDSCRIPT = nrf51822_master
MCU_SERIES = NRF51822
NRFSDK_ROOT := ./NRF5_SDK

NRF_SEPARATE = master

#NRFCFLAGS += -DNRF_LOG_BACKEND_SERIAL_USES_UART=1
#NRFCFLAGS += -DNRF_LOG_BACKEND_SERIAL_UART_TX_PIN=19

#NRFCFLAGS += -DNRF_LOG_BACKEND_UART_TX_PIN=19
#NRFCFLAGS += -DNRF_SDH_BLE_LOG_LEVEL=4
